/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.inatel.ec212.view;

import br.com.inatel.ec212.model.JBSDF;
import br.com.inatel.ec212.model.JCamera;
import br.com.inatel.ec212.model.JFilm;
import br.com.inatel.ec212.model.JRenderOptions;
import br.com.inatel.ec212.model.JRenderer;
import br.com.inatel.ec212.model.JScene;
import br.com.inatel.ec212.model.JShape;
import br.com.inatel.ec212.model.JSphere;
import com.badlogic.gdx.math.Matrix4;
import com.badlogic.gdx.math.Vector3;
import java.awt.image.BufferedImage;
import java.awt.image.IndexColorModel;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class ViewPort extends javax.swing.JFrame {

    /**
     * Creates new form ViewPort
     */
    public ViewPort() {
        initComponents();
                
        JRenderOptions renderOptions = new JRenderOptions(500, 500, 16, (float)2.0, (float)2.2, (float)0);
        JFilm film = new JFilm(renderOptions.getWidth(), renderOptions.getHeight());
        
        JCamera camera = new JCamera((float)Math.toRadians(20), film, new Matrix4());
        camera.lookAt(new Vector3( 0, 0, 35 ), Vector3.Zero, new Vector3( 0, 1, 0 ));
        
        JBSDF whiteMaterial = new JBSDF(JBSDF.JBSDF_Type.Diffuse, new Vector3(1, 1, 1));
        
        JSphere sphere = new JSphere(Vector3.Zero, (float) 2, whiteMaterial);
        
        ArrayList<JShape> shapes = new ArrayList();
        shapes.add(sphere);
        
        JScene scene = new JScene(shapes);
        JRenderer renderer = new JRenderer(renderOptions, camera, scene);
        
        BufferedImage bufferedImage = renderer.render();
        ImageIcon imageIcon = new ImageIcon(bufferedImage);
        imageView.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());
        getContentPane().add(imageView, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageView;
    // End of variables declaration//GEN-END:variables
}
